version: '3.8'

services:
  ffc-future-grants-file-store:
    build:
      context: .
      target: production
    image: ffc-future-grants-file-store
    container_name: ffc-future-grants-file-store
    depends_on:
      - ffc-future-grants-file-store-postgres
    environment:
      POSTGRES_DB: ffc_future_grants_file_store
      POSTGRES_PASSWORD: ppp
      POSTGRES_USER: adminuser@sndffcdbssq1002
      POSTGRES_HOST: ffc-future-grants-file-store-postgres
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: public
      SERVICE_BUS_HOST: ${SERVICE_BUS_HOST:-notset}
      SERVICE_BUS_PASSWORD: ${SERVICE_BUS_PASSWORD:-notset}
      SERVICE_BUS_USER: ${SERVICE_BUS_USER:-notset}
      APPLICATION_REQUEST_QUEUE_ADDRESS: ${APPLICATION_REQUEST_QUEUE_ADDRESS:-notset}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      FILE_STORE_QUEUE_ADDRESS: ${FILE_STORE_QUEUE_ADDRESS:-notset}
      USER_DATA_REQ_QUEUE_ADDRESS: ${USER_DATA_REQ_QUEUE_ADDRESS:-notset}
      USER_DATA_RES_QUEUE_ADDRESS: ${USER_DATA_RES_QUEUE_ADDRESS:-notset}
      FILES_STORED_TOPIC_ADDRESS: ${FILES_STORED_TOPIC_ADDRESS:-notset}

  ffc-future-grants-file-store-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_future_grants_file_store
      POSTGRES_PASSWORD: ppp
      POSTGRES_USER: postgres
      APPINSIGHTS_CLOUDROLE: ffc-grants-desirability
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY:-notset}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
