{{- include "ffc-helm-library.container-config-map" (list . "ffc-future-grants-file-store.config-map") -}}
{{- define "ffc-future-grants-file-store.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  NAMESPACE: {{ quote .Values.namespace }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  APPLICATION_REQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationRequestQueueAddress }}
  FILE_STORE_QUEUE_ADDRESS: {{ quote .Values.container.fileStoreQueueAddress }}
  USER_DATA_REQ_QUEUE_ADDRESS: {{ quote .Values.container.userDataReqQueueAddress }}
  USER_DATA_RES_QUEUE_ADDRESS: {{ quote .Values.container.userDataResQueueAddress }}
  APPLICATION_RESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.applicationResponseQueueAddress }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  MESSAGE_QUEUE_USER: {{ .Values.container.messageQueueUser }}
  MESSAGE_QUEUE_PASSWORD: {{ .Values.container.messageQueuePassword }}
  FILES_STORED_TOPIC_ADDRESS: {{ quote .Values.container.filesStoredTopicAddress }}
  POSTGRES_DB: {{ quote .Values.container.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.container.postgresqlHost }}
  POSTGRES_USER: {{ quote .Values.container.postgresUser }}
  POSTGRES_PASSWORD: {{ quote .Values.container.fileStorePostgresPassword }}
{{- end -}}