{{- include "ffc-helm-library.container-secret" (list . "ffc-future-grants-file-store.container-secret") -}}
{{- define "ffc-future-grants-file-store.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  POSTGRES_DB: {{ .Values.container.postgresDb | quote }}
  POSTGRES_HOST: {{ .Values.container.postgresHost | quote }}
{{- end -}}