{{- include "ffc-helm-library.container-secret" (list . "ffc-future-grants-file-store.container-secret") -}}
{{- define "ffc-future-grants-file-store.container-secret" -}}
stringData:
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  POSTGRES_USER: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}