apiVersion: v2
description: file-store postgres DB for the grants apply journey
name: ffc-future-grants-file-store
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/