environment: development
name: ffc-future-grants-file-store
namespace: ffc-future-grants
workstream: ffc-future-grants
image: ffc-future-grants-file-store

labels: {}

aadPodIdentity: true

appInsights:
  connectionString:

azureIdentity:
  clientID: dummy
  resourceID: dummy

containerConfigMap:
  name: ffc-future-grants-file-store-config-map

containerSecret:
  name: ffc-future-grants-file-store-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 2
  maxReplicas: 3
  priorityClassName: default
  replicas: 2
  restartPolicy: Always
  redeployOnChange: update this field to force a change

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 400Mi
  limitCpu: 120m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  applicationRequestQueueAddress: ffc-future-grants-application-request
  fileStoreQueueAddress: ffc-future-grants-file-data
  userDataReqQueueAddress: dummy
  userDataResQueueAddress: dummy
  filesStoredTopicAddress: dummy
  applicationResponseQueueAddress: ffc-future-grants-application-response
  messageQueueHost: namespace.servicebus.windows.net
  messageQueueUser: dummy
  messageQueuePassword: dummy
  port: 3000
  postgresDb: dummy
  postgresqlHost: dummy

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5