environment: development
name: ffc-future-grants-file-store
namespace: ffc-future-grants
workstream: ffc-future-grants
image: ffc-future-grants-file-store

labels: {}

aadPodIdentity: true

postgresService:
  postgresDb: ffc_future_grants_file_store
  postgresExternalName:
  postgresqlHost: ffc-future-grants-file-store-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

appInsights:
  key: not-a-real-key

azureIdentity:
  clientID: dummy
  resourceID: dummy

containerConfigMap:
  name: ffc-future-grants-file-store-config-map

containerSecret:
  name: ffc-future-grants-file-store-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  minReadySeconds: 0
  redeployOnChange: update this field to force a change
  replicas: 2
  minReplicas: 2
  maxReplicas: 3
  cpuThreshold: 80
  memoryThreshold: 80

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  messageQueueHost: dummy
  fileStoreQueueAddress: ffc-future-grants-file-data
  userDataReqQueueAddress: ffc-future-grants-user-file-data-req
  userDataResQueueAddress: ffc-future-grants-user-file-data-res
  filesStoredTopicAddress: ffc-future-grants-files-stored
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 20
  failureThreshold: 3
