environment: development
name: ffc-future-grants-file-store
namespace: ffc-future-grants
workstream: ffc-future-grants
image: ffc-future-grants-file-store

labels: {}

aadPodIdentity: true

appInsights:
  connectionString:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-future-grants-file-store-config-map

containerSecret:
  name: ffc-future-grants-file-store-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 2
  maxReplicas: 4
  priorityClassName: high
  replicas: 2
  restartPolicy: Always
  redeployOnChange: update this field to force a change

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 400Mi
  limitCpu: 400m
  fileCreatedTopicAddress: file-created
  fileCreatedSubscriptionAddress: file-sender
  protectiveMonitoringUrl:
  applicationRequestQueueAddress: ffc-future-grants-application-request
  fileStoreQueueAddress: ffc-future-grants-file-data
  userDataRequestQueueAddress:
  userDataResponseQueueAddress:
  applicationResponseQueueAddress: ffc-future-grants-application-response
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  eventQueueAddress: ffc-ahwr-event
  messageQueueHost: namespace.servicebus.windows.net
  port: 3000
  redisHostname: redis-hostname.default
  redisPartition: ffc-future-grants-apply
  redisPassword: redis
  redisPort: 6379
  urlPrefix: /apply
  registerYourInterestRequestQueueAddress: ffc-ahwr-register-your-interest-request
  defraIdTenant:
  defraIdRedirectUri:
  defraIdJwtIssuerId:
  defraIdClientId:
  defraIdClientSecret:
  defraIdServiceId:
  defraIdPolicy:
  rpaHostname:
  blobStorageAccountName: blob-account
  blobStorageContainerName: not-a-real-container
  blobStorageConnectionString: dummy
  claimFormDownloadUrl: dummy
  rpaGetPersonSummaryUrl:
  rpaGetOrganisationPermissionsUrl:
  rpaGetOrganisationUrl:
  rpaGetCphNumbersUrl:
  apimOcpSubscriptionKey:
  apimHostname:
  apimOAuthPath:
  apimClientId:
  apimClientSecret:
  apimScope:
  useBlobStorageConnectionString: false

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5